### ISSUE TITLE
Any example on how to push lists to the graph db ?

### ISSUE THREAD

**Issue by rohankk2** [Azure-Samples/azure-cosmos-db-graph-gremlindotnet-getting-started#10]
Since we are using gremlin strings to execute the gremlin queries, is there any way I can make the property of a vertex to be a list value ?

**Comment by alexdrenea** [comment]
I'd be interested if there's a native way of doing that too..

In the meantime, as a workaround I am saving lists as a Json Serizalized string. This works for arrays or any other kind of complex property

**Comment by olivertowers** [comment]
Gremlin vertices support properties with list cardinality, where they can have multiple values.

Example:
Using `list` modifier on `property` step will append items to the property values.
      
    g.V('id0').property(list, 'myProp', 'a').property(list, 'myProp', 'b')

Vertex property filters will match if any property value matches the predicate eg.

    g.V().has('myProp', 'b') 

Match vertices for multiple values for the same property

    g.V().has('myProp', 'b').has('myProp', 'a')

To delete a property value:

    g.V('id0').properties('myProp').hasValue('a').drop()

Overwrite the property value list:

    g.V('id0').property(single, 'myProp', 'overwrite')
