### ISSUE TITLE
program crashes 

### ISSUE THREAD

**Issue by mdemarco1234** [Azure-Samples/azure-cosmos-db-graph-gremlindotnet-getting-started#19]
"g.V().drop()" }, causes the bottom to happen

System.AggregateException: 'One or more errors occurred. (ServerError: 

ActivityId : 00000000-0000-0000-0000-000000000000
ExceptionType : DocumentClientException
ExceptionMessage :
	Message: {"Errors":["Resource Not Found. Learn more: https:\/\/aka.ms\/cosmosdb-tsg-not-found"]}
	ActivityId: 8bd9c00a-7efb-41ff-829a-4a38e27ae7d7, Request URI: /apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats: 
	RequestStartTime: 2021-05-02T17:14:12.6027433Z, RequestEndTime: 2021-05-02T17:14:12.6192675Z,  Number of regions attempted:1
	ResponseTime: 2021-05-02T17:14:12.6192675Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10251/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 22, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#22, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read
	ResponseTime: 2021-05-02T17:14:12.6192675Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10251/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 22, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#22, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read
	, SDK: Microsoft.Azure.Documents.Common/2.11.0, documentdb-dotnet-sdk/2.11.0 Host/64-bit MicrosoftWindowsNT/6.2.9200.0
Source : Microsoft.Azure.Documents.ClientMessage: {"Errors":["Resource Not Found. Learn more: https:\/\/aka.ms\/cosmosdb-tsg-not-found"]}
ActivityId: 8bd9c00a-7efb-41ff-829a-4a38e27ae7d7, Request URI: /apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats: 
RequestStartTime: 2021-05-02T17:14:12.6027433Z, RequestEndTime: 2021-05-02T17:14:12.6192675Z,  Number of regions attempted:1
ResponseTime: 2021-05-02T17:14:12.6192675Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10251/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 22, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#22, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read
ResponseTime: 2021-05-02T17:14:12.6192675Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10251/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 22, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#22, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read
, SDK: Microsoft.Azure.Documents.Common/2.11.0, documentdb-dotnet-sdk/2.11.0 Host/64-bit MicrosoftWindowsNT/6.2.9200.0
	BackendStatusCode : NotFound
	BackendActivityId : 8bd9c00a-7efb-41ff-829a-4a38e27ae7d7
	HResult : 0x80131500
)'

**Comment by olivertowers** [comment]
`Resource Not Found` error here is for access a collection/graph that does not exist:
` ...ResourceType: Collection, OperationType: Read...`

Does the collection you are targeting already exist? 

Per the [tutorial](https://docs.microsoft.com/en-us/azure/cosmos-db/create-graph-dotnet) for this sample, the collection/graph needs to be pre-created.

**Comment by olivertowers** [comment]
Closing issue as inactive
