### ISSUE TITLE
Update version of Gremlin.Net from 3.2.7 to latest in the repository.  

### ISSUE THREAD

**Issue by RebelSyntax** [Azure-Samples/azure-cosmos-db-graph-gremlindotnet-getting-started#3]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
clone the repository, restore nuget packages

### Any log messages given by the failure
>
Program.cs Line 58
`using (var gremlinClient = new GremlinClient(gremlinServer, new GraphSON2Reader(), new GraphSON2Writer(), GremlinClient.GraphSON2MimeType))`

"'GremlinClient' does not contain a constructor that takes 4 arguments"

Also, each of the types in the arguments are not found.  

### Expected/desired behavior
>
expected to build successfully

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
windows 10 Professional 
visual studio 15.6.4
### Versions
>
### Mention any other details that might be useful
packages.config Line 3
`<package id="Gremlin.Net" version="3.2.7" targetFramework="net461" />`

I noticed the other couple of reported documentation/issues that talked about compatibility etc..

I updated the packages to the latest Gremlin.Net v3.3.1

and that solved the above issues.  So I suppose the package file in this repository needs to be updated.  

I am moving on to see if I can make this sample work.  I hope that my report here will be found useful.

Thank you and I look forward to working with that technology.  
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by LuisBosquez** [comment]
@RebelSyntax Thanks for bringing this up. This is now fixed.
