### ISSUE TITLE
Websocket connection to CosmosDB graph is unstable

### ISSUE THREAD

**Issue by danielcweber** [Azure-Samples/azure-cosmos-db-graph-gremlindotnet-getting-started#5]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Checkout the 'FlakyWebsocket' branch from this repo: https://github.com/danielcweber/azure-cosmos-db-graph-gremlindotnet-getting-started/commits/FlakyWebsocket. Build and run. The sample is supposed to run in an in finite loop, however, CosmosDB seems to close the connection at some random point (sometimes after 15 seconds, sometimes 30, sometimes 4 minutes).

### Any log messages given by the failure

The most inner exception is a socket exception with native error code 10054 (sorry, german):

> System.Net.Sockets.SocketException (0x80004005): Eine vorhandene Verbindung wurde vom Remotehost geschlossen
   bei System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   bei System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)

### Expected/desired behavior
Run forever, keep the websocket connection alive.

### OS and Version?
Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

Windows 10,

### Versions
.net 4.6.1., Gremlinq.net 3.3.1, tested with Gremlinq.net 3.3.2 as well, same results.

### Mention any other details that might be useful
The issue is not related to a too large request rate. You can adjust the wait interval, it won't make any difference. The metrics in the CosmosDB dashboard suggest that the used RU/s is way below what is reserved.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dmykra** [comment]
having the same problem, did you find a solution?

**Comment by danielcweber** [comment]
Seemed to be pretty stable lately...but I can't say for sure whether it'll persist...

**Comment by dmykra** [comment]
it stabilizied here as well now...

the issue arouse all of a sudden, and lasted for about a week. now, I am no longer able to reproduce the exception no matter what, weird.
