### ISSUE TITLE
Performance ordering gremlin query results 

### ISSUE THREAD

**Issue by wpitallo** [Azure-Samples/azure-cosmos-db-graph-gremlindotnet-getting-started#9]
Hi, I hope that someone could please help me. I have setup a simple test to test query performance for a basic social network.  I have included the code below. Basically what I do is create 30000 vertices and then create 20000 edges on one of the vertices. 

 When I run the following query results are returned quickly: g.V().hasId('partition1').out('friendsWith').valueMap('name', 'profilePicture').range(0,2)

However, as soon as I add an order clause the query takes much, much longer. Over a minute to complete: 
g.V().hasId('partition1').out('friendsWith').order().by('name', incr).valueMap('name', 'profilePicture').range(0,2)

Is there a way to index the graph to speed this type of query up? 

Thanks very much for the help!

       public async Task<bool> runTests(Models.Person person)
        {
            try
            {
                var gremlinServer = new GremlinServer(_hostname, _port, enableSsl: true,
                                                   username: "/dbs/" + _dataBaseId + "/colls/" + _collectionId,
                                                   password: _authKey);

                using (var gremlinClient = new GremlinClient(gremlinServer, new GraphSON2Reader(), new GraphSON2Writer(), GremlinClient.GraphSON2MimeType))
                {
                    await gremlinClient.SubmitAsync<dynamic>("g.E().drop()");
                    await gremlinClient.SubmitAsync<dynamic>("g.V().drop()");

                    var counter = 30000;
                    while (counter != 0)
                    {
                        await gremlinClient.SubmitAsync<dynamic>("g.addV('partition" + counter + "').property('id', 'partition" + counter + "').property('profilePicture', '" + person.ProfilePicture + "').property('name', 'Person " + counter + "').property('partitionKey', 'partition" + counter + "')");
                        counter--;
                    }

                    var counter = 20000;
                    while (counter != 0)
                    {
                        int num = counter + 1;
                        var personToLink = "partition" + num;
                        await gremlinClient.SubmitAsync<dynamic>("g.V('partition1').addE('friendsWith').to(g.V('partition" + num + "'))");
                        counter--;
                    }

                    var searchResults = await gremlinClient.SubmitAsync<dynamic>("g.V().hasId('partition1').out('friendsWith').order().by('name', incr).valueMap('name', 'profilePicture').range(0,2)");

                    return true;
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

**Comment by olivertowers** [comment]
Order-by on non-source steps (any case that isn't `g.V().order().by()` or `g.E().order().by()`) will involve a runtime scan/order-by rather than utilizing the index which is a known limitation. 
Recommendation is to apply any additional filters on the `out()` step to reduce the size of the data set that needs to be sorted.
